<?php
/**
 * Plugin Name: WC2026 Schedule
 * Plugin URI:  https://github.com/camaleaun/camaleaun-worldcup2026
 * Description: FIFA World Cup 2026™ interactive schedule block — calendar, matches, groups and knockout bracket with live score tracking.
 * Version:     2.0.0
 * Author:      camaleaun
 * Text Domain: camaleaun-worldcup2026
 * Domain Path: /languages
 * Requires at least: 6.4
 * Requires PHP:      8.0
 *
 * @package WC2026Schedule
 */

defined( 'ABSPATH' ) || exit;

define( 'WC2026_PLUGIN_DIR', plugin_dir_path( __FILE__ ) );
define( 'WC2026_PLUGIN_URL', plugin_dir_url( __FILE__ ) );
define( 'WC2026_VERSION',    '2.0.0' );

require_once WC2026_PLUGIN_DIR . 'includes/class-cwc26-db.php';
require_once WC2026_PLUGIN_DIR . 'includes/class-cwc26-seeder.php';
require_once WC2026_PLUGIN_DIR . 'includes/class-cwc26-rest.php';
require_once WC2026_PLUGIN_DIR . 'includes/class-cwc26-admin.php';

register_activation_hook( __FILE__, [ 'CWC26_DB', 'install' ] );
register_uninstall_hook( __FILE__, [ 'CWC26_DB', 'uninstall' ] );

CWC26_REST::init();
CWC26_Admin::init();

/**
 * Load plugin text domain for PHP strings.
 */
function wc2026_load_textdomain(): void {
	load_plugin_textdomain(
		'camaleaun-worldcup2026',
		false,
		dirname( plugin_basename( __FILE__ ) ) . '/languages'
	);
}
add_action( 'init', 'wc2026_load_textdomain' );

/**
 * Register scripts, styles, and the block type.
 *
 * The build/ directory is generated by `npm run build`.
 * asset.php files are auto-generated by @wordpress/scripts and list
 * exact dependency handles and a content hash for cache busting.
 */
function wc2026_register_block(): void {
	$build = WC2026_PLUGIN_DIR . 'build/';
	$url   = WC2026_PLUGIN_URL . 'build/';

	// ── Editor script ────────────────────────────────────────────────────
	$editor_asset = file_exists( $build . 'index.asset.php' )
		? require $build . 'index.asset.php'
		: [ 'dependencies' => [ 'wp-blocks', 'wp-element', 'wp-block-editor', 'wp-components', 'wp-i18n' ], 'version' => '2.0.0' ];

	wp_register_script(
		'wc2026-editor',
		$url . 'index.js',
		$editor_asset['dependencies'],
		$editor_asset['version'],
		false
	);
	wp_set_script_translations( 'wc2026-editor', 'camaleaun-worldcup2026', WC2026_PLUGIN_DIR . 'languages' );

	// ── Frontend script ──────────────────────────────────────────────────
	$frontend_asset = file_exists( $build . 'frontend.asset.php' )
		? require $build . 'frontend.asset.php'
		: [ 'dependencies' => [ 'react', 'react-dom', 'wp-i18n' ], 'version' => '2.0.0' ];

	wp_register_script(
		'wc2026-frontend',
		$url . 'frontend.js',
		$frontend_asset['dependencies'],
		$frontend_asset['version'],
		true
	);
	wp_set_script_translations( 'wc2026-frontend', 'camaleaun-worldcup2026', WC2026_PLUGIN_DIR . 'languages' );

	// ── Styles ───────────────────────────────────────────────────────────
	// frontend.css → loaded on both frontend and editor (via block.json "style")
	wp_register_style( 'wc2026-style', $url . 'frontend.css', [], '2.0.0' );
	// index.css    → editor-only (via block.json "editorStyle")
	wp_register_style( 'wc2026-editor-style', $url . 'index.css', [ 'wc2026-style' ], '2.0.0' );

	// ── Block type ────────────────────────────────────────────────────────
	register_block_type(
		WC2026_PLUGIN_DIR . 'block.json',
		[ 'render_callback' => 'wc2026_render_block' ]
	);
}
add_action( 'init', 'wc2026_register_block' );

/**
 * Render callback — outputs the block container and inlines match data.
 *
 * The JSON data (~27 KB) is inlined once per page as `window.WC2026Data`
 * so the React app can access it without an extra HTTP request.
 *
 * @param array  $attributes Block attributes.
 * @return string            Block HTML.
 */
function wc2026_render_block( array $attributes ): string {
	// Enqueue frontend script + style.
	wp_enqueue_script( 'wc2026-frontend' );
	wp_enqueue_style( 'wc2026-style' );

	// Inline schedule data exactly once per page — sourced from DB when available.
	static $data_inlined = false;
	if ( ! $data_inlined ) {
		$json = wc2026_build_schedule_json();
		wp_add_inline_script( 'wc2026-frontend', 'window.WC2026Data=' . $json . ';', 'before' );
		$data_inlined = true;
	}

	$default_tab  = sanitize_key( $attributes['defaultTab']  ?? 'calendar' );
	$results_url  = esc_url( $attributes['resultsUrl'] ?? '' );
	$block_id     = 'wc2026-' . wp_unique_id();
	$align_class  = ! empty( $attributes['align'] ) ? ' align' . sanitize_key( $attributes['align'] ) : ' alignwide';

	return sprintf(
		'<div id="%1$s" class="wc2026-schedule%2$s wp-block-wc2026-schedule"
			data-default-tab="%3$s"
			data-results-url="%4$s">
			<noscript><p>%5$s</p></noscript>
		</div>',
		esc_attr( $block_id ),
		esc_attr( $align_class ),
		esc_attr( $default_tab ),
		esc_attr( $results_url ),
		esc_html__( 'Please enable JavaScript to view the FIFA World Cup 2026™ schedule.', 'camaleaun-worldcup2026' )
	);
}

/**
 * Build the WC2026Data JSON payload for the frontend.
 *
 * Falls back to src/data.json when the DB tables are not yet installed.
 */
function wc2026_build_schedule_json(): string {
	global $wpdb;

	// Fallback: DB not installed yet.
	if ( ! get_option( CWC26_DB::OPTION_KEY ) ) {
		$path = WC2026_PLUGIN_DIR . 'src/data.json';
		return file_exists( $path ) ? file_get_contents( $path ) : '{}'; // phpcs:ignore
	}

	// ── Teams ────────────────────────────────────────────────────────────
	$team_rows = $wpdb->get_results(
		'SELECT fifa_code, name, flag_iso, ranking FROM ' . CWC26_DB::teams(),
		ARRAY_A
	);
	$teams = [];
	foreach ( $team_rows as $r ) {
		$teams[ $r['fifa_code'] ] = [
			'name'     => $r['name'],
			'flag_url' => WC2026_PLUGIN_URL . 'assets/flags/' . strtolower( $r['fifa_code'] ) . '.svg',
			'ranking'  => $r['ranking'] ? (int) $r['ranking'] : null,
		];
	}

	// ── Stadiums ─────────────────────────────────────────────────────────
	$stad_rows = $wpdb->get_results(
		'SELECT roman_id, city, name FROM ' . CWC26_DB::stadiums(),
		ARRAY_A
	);
	$stadiums = [];
	foreach ( $stad_rows as $r ) {
		$stadiums[ $r['roman_id'] ] = [ 'city' => $r['city'], 'name' => $r['name'] ];
	}

	// ── Matches ──────────────────────────────────────────────────────────
	$match_rows = $wpdb->get_results(
		'SELECT * FROM ' . CWC26_DB::matches() . ' ORDER BY match_utc ASC',
		ARRAY_A
	);

	$groups   = [];
	$knockout = [ 'round_of_32' => [], 'round_of_16' => [], 'quarter_finals' => [], 'semi_finals' => [], 'finals' => [] ];
	$round_key = [ 'r32' => 'round_of_32', 'r16' => 'round_of_16', 'qf' => 'quarter_finals', 'sf' => 'semi_finals', 'f' => 'finals', 'po' => 'finals' ];

	foreach ( $match_rows as $m ) {
		$match = [
			'id'           => (int) $m['match_id'],
			'round'        => $m['round'],
			'utc'          => str_replace( ' ', 'T', $m['match_utc'] ) . 'Z',
			'stadium'      => $m['stadium_id'],
			'home'         => $m['home_code'],
			'away'         => $m['away_code'],
			'home_score'   => isset( $m['home_score'] ) ? (int) $m['home_score'] : null,
			'away_score'   => isset( $m['away_score'] ) ? (int) $m['away_score'] : null,
			'match_status' => $m['match_status'],
		];

		if ( 'group' === $m['phase'] ) {
			$letter = $m['group_letter'];
			if ( ! isset( $groups[ $letter ] ) ) {
				// Fetch team order from cwc26_groups.
				$team_rows2 = $wpdb->get_results( $wpdb->prepare(
					'SELECT team_code FROM ' . CWC26_DB::groups() . ' WHERE group_letter = %s ORDER BY position ASC',
					$letter
				), ARRAY_A );
				$groups[ $letter ] = [ 'teams' => array_column( $team_rows2, 'team_code' ), 'matches' => [] ];
			}
			$groups[ $letter ]['matches'][] = $match;
		} else {
			$key = $round_key[ $m['round'] ] ?? 'finals';
			$knockout[ $key ][] = $match;
		}
	}

	return wp_json_encode( compact( 'teams', 'stadiums', 'groups', 'knockout' ) );
}
