<?php
/**
 * Plugin Name: WC2026 Schedule
 * Plugin URI:  https://github.com/camaleaun/camaleaun-worldcup2026
 * Description: FIFA World Cup 2026™ interactive schedule block — calendar, matches, groups and knockout bracket with live score tracking.
 * Version:     2.0.0
 * Author:      camaleaun
 * Text Domain: camaleaun-worldcup2026
 * Domain Path: /languages
 * Requires at least: 6.4
 * Requires PHP:      8.0
 *
 * @package WC2026Schedule
 */

defined( 'ABSPATH' ) || exit;

define( 'WC2026_PLUGIN_DIR', plugin_dir_path( __FILE__ ) );
define( 'WC2026_PLUGIN_URL', plugin_dir_url( __FILE__ ) );

/**
 * Load plugin text domain for PHP strings.
 */
function wc2026_load_textdomain(): void {
	load_plugin_textdomain(
		'camaleaun-worldcup2026',
		false,
		dirname( plugin_basename( __FILE__ ) ) . '/languages'
	);
}
add_action( 'init', 'wc2026_load_textdomain' );

/**
 * Register scripts, styles, and the block type.
 *
 * The build/ directory is generated by `npm run build`.
 * asset.php files are auto-generated by @wordpress/scripts and list
 * exact dependency handles and a content hash for cache busting.
 */
function wc2026_register_block(): void {
	$build = WC2026_PLUGIN_DIR . 'build/';
	$url   = WC2026_PLUGIN_URL . 'build/';

	// ── Editor script ────────────────────────────────────────────────────
	$editor_asset = file_exists( $build . 'index.asset.php' )
		? require $build . 'index.asset.php'
		: [ 'dependencies' => [ 'wp-blocks', 'wp-element', 'wp-block-editor', 'wp-components', 'wp-i18n' ], 'version' => '2.0.0' ];

	wp_register_script(
		'wc2026-editor',
		$url . 'index.js',
		$editor_asset['dependencies'],
		$editor_asset['version'],
		false
	);
	wp_set_script_translations( 'wc2026-editor', 'camaleaun-worldcup2026', WC2026_PLUGIN_DIR . 'languages' );

	// ── Frontend script ──────────────────────────────────────────────────
	$frontend_asset = file_exists( $build . 'frontend.asset.php' )
		? require $build . 'frontend.asset.php'
		: [ 'dependencies' => [ 'react', 'react-dom', 'wp-i18n' ], 'version' => '2.0.0' ];

	wp_register_script(
		'wc2026-frontend',
		$url . 'frontend.js',
		$frontend_asset['dependencies'],
		$frontend_asset['version'],
		true
	);
	wp_set_script_translations( 'wc2026-frontend', 'camaleaun-worldcup2026', WC2026_PLUGIN_DIR . 'languages' );

	// ── Styles ───────────────────────────────────────────────────────────
	// frontend.css → loaded on both frontend and editor (via block.json "style")
	wp_register_style( 'wc2026-style', $url . 'frontend.css', [], '2.0.0' );
	// index.css    → editor-only (via block.json "editorStyle")
	wp_register_style( 'wc2026-editor-style', $url . 'index.css', [ 'wc2026-style' ], '2.0.0' );

	// ── Block type ────────────────────────────────────────────────────────
	register_block_type(
		WC2026_PLUGIN_DIR . 'block.json',
		[ 'render_callback' => 'wc2026_render_block' ]
	);
}
add_action( 'init', 'wc2026_register_block' );

/**
 * Render callback — outputs the block container and inlines match data.
 *
 * The JSON data (~27 KB) is inlined once per page as `window.WC2026Data`
 * so the React app can access it without an extra HTTP request.
 *
 * @param array  $attributes Block attributes.
 * @return string            Block HTML.
 */
function wc2026_render_block( array $attributes ): string {
	// Enqueue frontend script + style.
	wp_enqueue_script( 'wc2026-frontend' );
	wp_enqueue_style( 'wc2026-style' );

	// Inline match JSON exactly once per page.
	static $data_inlined = false;
	if ( ! $data_inlined ) {
		$json_path = WC2026_PLUGIN_DIR . 'src/data.json';
		if ( file_exists( $json_path ) ) {
			$json = file_get_contents( $json_path ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
			wp_add_inline_script( 'wc2026-frontend', 'window.WC2026Data=' . $json . ';', 'before' );
		}
		$data_inlined = true;
	}

	$default_tab  = sanitize_key( $attributes['defaultTab']  ?? 'calendar' );
	$results_url  = esc_url( $attributes['resultsUrl'] ?? '' );
	$block_id     = 'wc2026-' . wp_unique_id();
	$align_class  = ! empty( $attributes['align'] ) ? ' align' . sanitize_key( $attributes['align'] ) : ' alignwide';

	return sprintf(
		'<div id="%1$s" class="wc2026-schedule%2$s wp-block-wc2026-schedule"
			data-default-tab="%3$s"
			data-results-url="%4$s">
			<noscript><p>%5$s</p></noscript>
		</div>',
		esc_attr( $block_id ),
		esc_attr( $align_class ),
		esc_attr( $default_tab ),
		esc_attr( $results_url ),
		esc_html__( 'Please enable JavaScript to view the FIFA World Cup 2026™ schedule.', 'camaleaun-worldcup2026' )
	);
}
